import type { Metadata } from "next";
import { Big_Shoulders_Display, JetBrains_Mono, Poppins } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/nav/Navbar";
import Footer from "@/components/footer/Footer";
const Big_Shoulders = Big_Shoulders_Display({
  subsets: ["latin"],
  variable: "--font-big-shoulders",
});
const poppins = Poppins({
  subsets: [],
  // variable: "--font-poppins",
  display: "swap",
  weight: ["400", "500", "600", "700", "800"],
});
const JetBrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))]
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} ${JetBrains.variable} ${Big_Shoulders.variable}`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
         
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
